// Interface automatically generated by schemas-to-ts

export interface NotificationTemplate {
  content: string;
  show?: boolean;
}
export interface NotificationTemplate_Plain {
  content: string;
  show?: boolean;
}

export interface NotificationTemplate_NoRelations {
  content: string;
  show?: boolean;
}

