// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Post } from './post';
import { Media_Plain } from '../common/Media';
import { Post_Plain } from './post';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Author {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    avatar?: { data: Media };
    posts: { data: Post[] };
  };
}
export interface Author_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  avatar?: Media_Plain;
  posts: Post_Plain[];
}

export interface Author_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  avatar?: number;
  posts: number[];
}

export interface Author_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  avatar?: AdminPanelRelationPropertyModification<Media_Plain>;
  posts: AdminPanelRelationPropertyModification<Post_Plain>;
}
