// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Global {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    logoDesktop: { data: Media };
    logoMobile: { data: Media };
    maintenanceMode?: boolean;
    favicon: { data: Media };
  };
}
export interface Global_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logoDesktop: Media_Plain;
  logoMobile: Media_Plain;
  maintenanceMode?: boolean;
  favicon: Media_Plain;
}

export interface Global_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logoDesktop: number;
  logoMobile: number;
  maintenanceMode?: boolean;
  favicon: number;
}

export interface Global_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logoDesktop: AdminPanelRelationPropertyModification<Media_Plain>;
  logoMobile: AdminPanelRelationPropertyModification<Media_Plain>;
  maintenanceMode?: boolean;
  favicon: AdminPanelRelationPropertyModification<Media_Plain>;
}
