// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Seo } from '../components/shared/Seo';
import { Author } from './author';
import { Media_Plain } from '../common/Media';
import { Seo_Plain } from '../components/shared/Seo';
import { Author_Plain } from './author';
import { Seo_NoRelations } from '../components/shared/Seo';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Post {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    description: string;
    slug?: string;
    cover: { data: Media };
    seo?: Seo;
    body: any;
    author: { data: Author };
  };
}
export interface Post_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  slug?: string;
  cover: Media_Plain;
  seo?: Seo_Plain;
  body: any;
  author: Author_Plain;
}

export interface Post_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  slug?: string;
  cover: number;
  seo?: Seo_NoRelations;
  body: any;
  author: number;
}

export interface Post_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  slug?: string;
  cover: AdminPanelRelationPropertyModification<Media_Plain>;
  seo?: Seo_Plain;
  body: any;
  author: AdminPanelRelationPropertyModification<Author_Plain>;
}
